export const REQUEST_STATS = "REQUEST_STATS";
export const REQUEST_STATS_SUCCESS = "REQUEST_STATS_SUCCESS";
export const REQUEST_STATS_FAIL = "REQUEST_STATS_FAIL";
export const SORT_BY_VALUE = "SORT_BY_VALUE";
export const SORT_BY_LABEL = "SORT_BY_LABEL";